CREATE TABLE [dbo].[LineSegment]
(
	[Uid] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Id] INT NOT NULL, 
    [Number] INT NULL, 
    [Name] NVARCHAR(50) NULL, 
    [Description] NVARCHAR(200) NULL, 
    [ParentTransmissionLine] UNIQUEIDENTIFIER NOT NULL, 
    [FromNode] UNIQUEIDENTIFIER NULL, 
    [ToNode] UNIQUEIDENTIFIER NULL, 
    [R1] FLOAT NOT NULL DEFAULT 0.0, 
    [R2] FLOAT NOT NULL DEFAULT 0.0, 
    [R3] FLOAT NOT NULL DEFAULT 0.0, 
    [R4] FLOAT NOT NULL DEFAULT 0.0, 
    [R5] FLOAT NOT NULL DEFAULT 0.0, 
    [R6] FLOAT NOT NULL DEFAULT 0.0, 
    [X1] FLOAT NOT NULL DEFAULT 0.01, 
    [X2] FLOAT NOT NULL DEFAULT 0.0, 
    [X3] FLOAT NOT NULL DEFAULT 0.01, 
    [X4] FLOAT NOT NULL DEFAULT 0.0, 
    [X5] FLOAT NOT NULL DEFAULT 0.0, 
    [X6] FLOAT NOT NULL DEFAULT 0.01, 
    [G1] FLOAT NOT NULL DEFAULT 0.0, 
    [G2] FLOAT NOT NULL DEFAULT 0.0, 
    [G3] FLOAT NOT NULL DEFAULT 0.0, 
    [G4] FLOAT NOT NULL DEFAULT 0.0, 
    [G5] FLOAT NOT NULL DEFAULT 0.0, 
    [G6] FLOAT NOT NULL DEFAULT 0.0, 
    [B1] FLOAT NOT NULL DEFAULT 0.0, 
    [B2] FLOAT NOT NULL DEFAULT 0.0, 
    [B3] FLOAT NOT NULL DEFAULT 0.0, 
    [B4] FLOAT NOT NULL DEFAULT 0.0, 
    [B5] FLOAT NOT NULL DEFAULT 0.0, 
    [B6] FLOAT NOT NULL DEFAULT 0.0, 
    [CreatedOn] TIME NOT NULL CONSTRAINT DF_LineSegment_CreatedOn DEFAULT(GETUTCDATE()), 
    [CreatedBy] NVARCHAR(200) NOT NULL CONSTRAINT DF_LineSegment_CreatedBy DEFAULT(SUSER_NAME()), 
    [LastEditedOn] TIME NOT NULL CONSTRAINT DF_LineSegment_LastEditedOn DEFAULT(GETUTCDATE()), 
    [LastEditedBy] NVARCHAR(200) NOT NULL CONSTRAINT DF_LineSegment_LastEditedBy DEFAULT(SUSER_NAME()), 
    CONSTRAINT [FK_LineSegment_TransmissionLine] FOREIGN KEY ([ParentTransmissionLine]) REFERENCES [TransmissionLine]([Uid]) ON DELETE CASCADE ON UPDATE CASCADE, 
    CONSTRAINT [FK_LineSegment_FromNode] FOREIGN KEY ([FromNode]) REFERENCES [Node]([Uid]), 
    CONSTRAINT [FK_LineSegment_ToNode] FOREIGN KEY ([ToNode]) REFERENCES [Node]([Uid]), 
    CONSTRAINT [CK_LineSegment_Id] CHECK (Id > 0), 
    CONSTRAINT [CK_LineSegment_Number] CHECK (Number > 0)
)

GO

CREATE INDEX [IX_LineSegment_Id] ON [dbo].[LineSegment] ([Id])

GO

CREATE TRIGGER [dbo].[Trigger_LineSegmentUpdate]
    ON [dbo].[LineSegment]
    FOR UPDATE
    AS
    BEGIN
        SET NoCount ON
		UPDATE [dbo].[LineSegment] SET LastEditedOn=GETUTCDATE() WHERE Uid in (SELECT Uid FROM INSERTED)
		UPDATE [dbo].[LineSegment] SET LastEditedBy=SUSER_NAME() WHERE Uid in (SELECT Uid FROM INSERTED)
    END